server:
  port: 8005
spring:
  application:
    name: service-feign
      #    链路追踪
  zipkin:
    base-url: http://119.23.255.144:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
#打开断路器
feign.hystrix.enabled: true

logging:
  level:
    org.springframework.cloud.netflix.feign: debug
