spring:
  application:
    name: service-ribbon
  #    链路追踪
  zipkin:
    base-url: http://119.23.255.144:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 8003